// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4O81GD0LzAGUUpaqCStqvk4QfPUCz9pk',
    appId: '1:436019358969:web:c85c8bdb71e12db9be4628',
    messagingSenderId: '436019358969',
    projectId: 'flutter-masterclass-575e9',
    authDomain: 'flutter-masterclass-575e9.firebaseapp.com',
    storageBucket: 'flutter-masterclass-575e9.appspot.com',
    measurementId: 'G-XPQTT6539S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClTiaGpVKXt_HljqrECYyuvqLPrnMfelc',
    appId: '1:436019358969:android:6b05d6029c543491be4628',
    messagingSenderId: '436019358969',
    projectId: 'flutter-masterclass-575e9',
    storageBucket: 'flutter-masterclass-575e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnrSPiS15OGFrG6Oca2wlj1cTeVWk2fcE',
    appId: '1:436019358969:ios:957e204fcc078ddcbe4628',
    messagingSenderId: '436019358969',
    projectId: 'flutter-masterclass-575e9',
    storageBucket: 'flutter-masterclass-575e9.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnrSPiS15OGFrG6Oca2wlj1cTeVWk2fcE',
    appId: '1:436019358969:ios:957e204fcc078ddcbe4628',
    messagingSenderId: '436019358969',
    projectId: 'flutter-masterclass-575e9',
    storageBucket: 'flutter-masterclass-575e9.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4O81GD0LzAGUUpaqCStqvk4QfPUCz9pk',
    appId: '1:436019358969:web:69e17aac1998760abe4628',
    messagingSenderId: '436019358969',
    projectId: 'flutter-masterclass-575e9',
    authDomain: 'flutter-masterclass-575e9.firebaseapp.com',
    storageBucket: 'flutter-masterclass-575e9.appspot.com',
    measurementId: 'G-PYPLF31M4T',
  );

}